clear -all

analyze -sv \
    ../../rtl/axicb_round_robin_core.sv \
    ../../rtl/axicb_round_robin.sv \
    ../props/rr_props.sv \
    ../bind1/rr_bind.sv \
    ../tb/rr_fpv_top.sv

elaborate \
    -top        rr_fpv_top \
    -parameter  REQ_NB              4   \
    -parameter  PRIORITY_W          2   \
    -parameter  NUM_PRIORITY_LVL    4

clock aclk
reset -expression {!aresetn}

#------------------------------------------------------------
# Sanity check and Reset phase analysis
#------------------------------------------------------------
sanity_check
visualize -reset

#------------------------------------------------------------
# Formal X-Propagation (FXP) Setup
# This command automatically extracts and generates 
# X-propagation properties based on the RTL structure.
#------------------------------------------------------------
check_xprop

set pass_label "rr_fxp"
set_prove_target_bound 80

# Keep your assumptions so the tool doesn't inject illegal 'X' states
assume -set_type -regexp .* approved

#------------------------------------------------------------
# Run proofs (This will now prove the properties generated by check_xprop)
#------------------------------------------------------------
prove -all

#------------------------------------------------------------
# Reporting
#------------------------------------------------------------
file mkdir ../../results

report \
    -results \
    -file "../../results/rr_fxp_results_${pass_label}.txt" \
    -force

report \
    -file "../../results/rr_fxp_waivers_${pass_label}.txt" \
    -force

# Added the detailed report from your sample script
report \
    -file "../../results/rr_fxp_summary_detailed_${pass_label}.txt" \
    -detailed \
    -force
